# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-10 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='\u94bb\u5b54\u7f16\u53f7')),
                ('coord_x', models.FloatField(verbose_name='X\u5750\u6807')),
                ('coord_y', models.FloatField(verbose_name='Y\u5750\u6807')),
                ('coord_z', models.FloatField(verbose_name='Z\u5750\u6807')),
                ('depth', models.FloatField(verbose_name='\u603b\u6df1\u5ea6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u94bb\u5b54\u57fa\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u94bb\u5b54\u57fa\u672c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='DrillLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='\u5206\u5c42\u7f16\u53f7')),
                ('layer_name', models.CharField(max_length=10, verbose_name='\u5206\u5c42\u540d\u79f0')),
                ('layer_des', models.TextField(null=True, verbose_name='\u5206\u5c42\u63cf\u8ff0')),
                ('top', models.FloatField(verbose_name='\u9876\u6df1')),
                ('bottom', models.FloatField(verbose_name='\u5e95\u6df1')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('drillBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.DrillBase', verbose_name='\u6240\u5c5e\u94bb\u5b54')),
            ],
            options={
                'verbose_name': '\u94bb\u5b54\u5206\u5c42\u4fe1\u606f',
                'verbose_name_plural': '\u94bb\u5b54\u5206\u5c42\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='DrillSampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='\u53d6\u6837\u7f16\u53f7')),
                ('d_from', models.FloatField(verbose_name='\u81ea')),
                ('d_to', models.FloatField(verbose_name='\u81f3')),
                ('length', models.FloatField(verbose_name='\u957f\u5ea6')),
                ('element1', models.FloatField(verbose_name='\u5143\u7d20\u4e00')),
                ('element2', models.FloatField(verbose_name='\u5143\u7d20\u4e8c')),
                ('element3', models.FloatField(verbose_name='\u5143\u7d20\u4e09')),
                ('element4', models.FloatField(verbose_name='\u5143\u7d20\u56db')),
                ('element5', models.FloatField(verbose_name='\u5143\u7d20\u4e94')),
                ('element6', models.FloatField(verbose_name='\u5143\u7d20\u516d')),
                ('element7', models.FloatField(verbose_name='\u5143\u7d20\u4e03')),
                ('element8', models.FloatField(verbose_name='\u5143\u7d20\u516b')),
                ('element9', models.FloatField(verbose_name='\u5143\u7d20\u4e5d')),
                ('element10', models.FloatField(verbose_name='\u5143\u7d20\u5341')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('drillBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.DrillBase', verbose_name='\u6240\u5c5e\u94bb\u5b54')),
            ],
            options={
                'verbose_name': '\u94bb\u5b54\u53d6\u6837\u4fe1\u606f',
                'verbose_name_plural': '\u94bb\u5b54\u53d6\u6837\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='DrillTilt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='\u9876\u6df1')),
                ('zenith', models.FloatField(verbose_name='\u9876\u89d2')),
                ('azimuth', models.FloatField(verbose_name='\u65b9\u4f4d\u89d2')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('drillBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.DrillBase', verbose_name='\u6240\u5c5e\u94bb\u5b54')),
            ],
            options={
                'verbose_name': '\u94bb\u5b54\u6d4b\u659c\u4fe1\u606f',
                'verbose_name_plural': '\u94bb\u5b54\u6d4b\u659c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='MiningArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u77ff\u533a', max_length=50, verbose_name='\u77ff\u533a\u540d\u79f0')),
                ('code', models.CharField(max_length=10, verbose_name='\u77ff\u533a\u7f16\u7801')),
                ('type', models.CharField(max_length=10, verbose_name='\u77ff\u79cd\u7c7b\u578b')),
                ('area', models.CharField(max_length=20, verbose_name='\u6240\u5728\u5730')),
                ('content', models.TextField(null=True, verbose_name='\u77ff\u533a\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u77ff\u533a\u4fe1\u606f',
                'verbose_name_plural': '\u77ff\u533a\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ProspectingLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='\u52d8\u63a2\u7ebf\u53f7')),
                ('coord_x', models.FloatField(verbose_name='X\u5750\u6807')),
                ('coord_y', models.FloatField(verbose_name='Y\u5750\u6807')),
                ('coord_z', models.FloatField(verbose_name='Z\u5750\u6807')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('miningArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.MiningArea', verbose_name='\u6240\u5c5e\u77ff\u533a')),
            ],
            options={
                'verbose_name': '\u52d8\u63a2\u7ebf\u4fe1\u606f',
                'verbose_name_plural': '\u52d8\u63a2\u7ebf\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='drillbase',
            name='miningArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.MiningArea', verbose_name='\u6240\u5c5e\u77ff\u533a'),
        ),
        migrations.AddField(
            model_name='drillbase',
            name='prospectingLine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.ProspectingLine', verbose_name='\u6240\u5c5e\u52d8\u63a2\u7ebf'),
        ),
    ]
